language: elixir
elixir:
  - 1.0.5
  - 1.1.1
  - 1.2.0
sudo: false
notifications:
  recipients:
    - jose.valim@plataformatec.com.br
otp_release:
  - 17.5
  - 18.1
env:
  - MIX_ENV=test
# after_script:
#   - mix deps.get --only docs
#   - MIX_ENV=docs mix inch.report
matrix:
  exclude:
    - otp_release: 17.5
      elixir: 1.2.0